Users/urls.py
from django.urls import path

from Users import views

app_name = 'Users'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login, name="login"),
]

Users/models.py
from django.db import models


# Create your models here.

class Users(models.Model):

    username = models.CharField('用户名', max_length=30, unique=True)

    password = models.CharField('密码', max_length=32)

    date_added = models.DateTimeField('创建时间', auto_now_add=True)

    update_date = models.DateTimeField('更新时间', auto_now=True)

    def __str__(self):
        return f"用户：{self.username} + {self.password}"

Users/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Users
from hashlib import md5

# Create your views here.
def index(request):
    return render(request, 'Users/index.html')

def register(request):
    if request.method == 'GET':
        return render(request, 'Users/register.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_c = request.POST['password_c']
        if password != password_c:
            return HttpResponse('输入密码不一致')
        if Users.objects.filter(username=username):
            return HttpResponse('用户已存在')
        p = md5()
        p.update(password.encode())
        password = p.hexdigest()
        try:
            new_user = Users.objects.create(username=username, password=password)
        except Exception as e:
            print('用户已注册')
            return HttpResponse('用户已注册')
        request.session['username'] = username
        request.session['uid'] = new_user.id
        response = HttpResponse('注册成功')
        response.set_cookie('username', new_user.username, max_age=30*24*3600)
        response.set_cookie('password', new_user.password, max_age=30*24*3600)
        return response
    else:
        pass
    context = {}
    return render(request, "Users/index.html", context)


def login(request):
    if request.method == 'GET':
        username = request.COOKIES.get('username')
        password = request.COOKIES.get('password')
        try:
            user = Users.objects.get(username=username)
        except Exception as e:
            print('用户名重复')
            return HttpResponse('用户名或密码不正确')
        if username == user.username and password == user.password:
            request.session['username'] = username
            request.session['uid'] = user.id
            return HttpResponse('登入成功')
        else:
            return HttpResponse('登入失败')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        p = md5()
        p.update(password.encode())
        password = p.hexdigest()
        try:
            user = Users.objects.get(username=username)
        except Exception as e:
            print('用户名重复')
            return HttpResponse('用户名或密码不正确')
        if username == user.username and password == user.password:
            request.session['username'] = username
            request.session['uid'] = user.id
            response = HttpResponse('登入成功')
            if request.POST['rem'] == 'on':
                response.set_cookie('username', user.username, max_age=30*24*3600)
                response.set_cookie('password', user.password, max_age=30*24*3600)
            return response
        else:
            return HttpResponse('登入失败')
    else:
        pass

Users/templates/Users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <p>
        你好，世界！！！
    </p>
    <p>
        <a href="{% url 'Users:register' %}">注册</a>
    </p>
    <p>
        <a href="{% url 'Users:login' %}">登入</a>
    </p>
</body>
</html>

Users/templates/Users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登入</title>
</head>
<body>
    <form action="{% url 'Users:login' %}" method="post">
        <p>
            用户名：<input type="text" name="username">
        </p>
        <p>
            密码：<input type="text" name="password">
        </p>
        <p>
            <input type="checkbox" name="rem">30天免登录
        </p>
        <p>
            <input type="submit" name="login" value="登录">
        </p>
    </form>
</body>
</html>

Users/templates/Users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="{% url 'Users:register' %}" method="post">
        <p>
            用户名：<input type="text" name="username">
        </p>
        <p>
            密码：<input type="text" name="password">
        </p>
        <p>
            确认密码：<input type="text" name="password_c">
        </p>
        <p>
            <input type="submit" name="提交">
        </p>
    </form>
</body>
</html>